product_item_loc = '.product-item:first-child .product-item-link'
product_size_loc = '//*[@id="option-label-size-143-item-171"]'
product_color_loc = '//*[@id="option-label-color-93-item-49"]'
button_add_cart_loc = 'button.action.tocart'
cart_button_loc = '/html/body/div[2]/header/div[2]/div[1]/a'
item_in_cart_loc = '//*[@id="mini-cart"]/li/div/div/strong'
page_message_loc = '//*[@id="maincontent"]/div[2]/div[2]/div/div/div'
switch_gape_loc = '//*[@id="maincontent"]/div[3]/div[1]/div[4]/div[2]/ul/li[3]/a'
sorted_items_loc = '.sorter'
price_item = '//*[@id="product-price-718"]'
new_price_item = '//*[@id="product-price-94"]'
action_sorted = '//*[@id="maincontent"]/div[3]/div[1]/div[2]/div[4]/a'
