fname_field_loc = '#firstname'
lname_field_loc = '#lastname'
email_field_loc = '#email_address'
pass_field_loc = '#password'
confirm_pass_field_loc = '#password-confirmation'
create_button_loc = '#form-validate > div > div.primary > button'
info_loc = '.box-content'
password_error_loc = '#password-error'
err_empty_field_fname = '#firstname-error'
page_message_loc = '//*[@id="maincontent"]/div[1]'
